### ISSUE TITLE
Chess.com pgn games cannot be loaded

### ISSUE THREAD

**Issue by deathcoder** [alexobviously/bishop#49]
when i try to load a pgn generated from chess.com i get an error:

```
The following RangeError was thrown running a test:
RangeError (end): Invalid value: Not in inclusive range 1..1226: -2

When the exception was thrown, this was the stack:
#0      RangeError.checkValidRange (dart:core/errors.dart:379:9)
#1      _StringBase.substring (dart:core-patch/string_patch.dart:398:27)
#2      parsePgn (package:bishop/src/pgn.dart:32:24)
```

here is the example i'm using:
```
1. d4 {[%clk 0:09:58.6]} 1... d5 {[%clk 0:09:58.1]} 2. Nc3 {[%clk 0:09:55.4]} 2... Bf5 {[%clk 0:09:55.4]} 3. f3 {[%clk 0:09:41.3]} 3... Nc6 {[%clk 0:09:49.9]} 4. e3 {[%clk 0:09:34.3]} 4... Nf6 {[%clk 0:09:47]} 5. g4 {[%clk 0:09:29.9]} 5... Nxg4 {[%clk 0:09:07.5]} 6. fxg4 {[%clk 0:09:19.3]} 6... Bxg4 {[%clk 0:08:39.9]} 7. Qxg4 {[%clk 0:09:16.8]} 7... Qd7 {[%clk 0:08:18.4]} 8. Qxd7+ {[%clk 0:08:51.6]} 8... Kxd7 {[%clk 0:08:15.6]} 9. Nxd5 {[%clk 0:08:47.5]} 9... e6 {[%clk 0:08:04.4]} 10. Nc3 {[%clk 0:08:24]} 10... Nb4 {[%clk 0:07:38.2]} 11. Kd1 {[%clk 0:07:38.9]} 11... c5 {[%clk 0:07:03.5]} 12. Nf3 {[%clk 0:07:20.1]} 12... Be7 {[%clk 0:06:10.2]} 13. Bh3 {[%clk 0:06:59.7]} 13... g5 {[%clk 0:05:48.1]} 14. Ng1 {[%clk 0:06:45.5]} 14... h5 {[%clk 0:05:25.2]} 15. Nf3 {[%clk 0:06:40.1]} 15... g4 {[%clk 0:05:16.4]} 16. Ne5+ {[%clk 0:06:08.1]} 16... Ke8 {[%clk 0:04:26.2]} 17. Bf1 {[%clk 0:05:56.5]} 17... f6 {[%clk 0:03:28.4]} 18. Nd3 {[%clk 0:05:42.6]} 18... Bd6 {[%clk 0:03:15]} 19. a3 {[%clk 0:05:13.6]} 19... Nd5 {[%clk 0:03:11.2]} 20. e4 {[%clk 0:04:56.2]} 20... Ne3+ {[%clk 0:03:08.4]} 21. Bxe3 {[%clk 0:04:42.9]} 21... g3 {[%clk 0:02:57.5]} 22. hxg3 {[%clk 0:04:39.6]} 22... Bxg3 {[%clk 0:02:54.2]} 23. Nxc5 {[%clk 0:04:29.5]} 1-0
```

my understanding is that the clk annotations are breaking the parser because they are enclosed in [ ] brackets...

this regex `r'((?<!\{)\[(.+)\])+'` seems to parse pgns containing the example above correctly

**Comment by alexobviously** [comment]
Hey, so I just merged this and upon testing a bit more realised there's still a problem. Lichess PGNs with clock annotations look like this:

```
1. e4 { [%clk 0:02:00] } 1... c6 { [%clk 0:02:00] } 2. Nc3 { [%clk 0:02:00] } 2... d5 { [%clk 0:02:01] } 3. d4 { [%clk 0:02:00] } 3... dxe4 { [%clk 0:02:01] } 4. Nxe4 { [%clk 0:02:01] } 4... Nf6 { [%clk 0:01:59] } 5. Nxf6+ { [%clk 0:02:00] } 5... exf6 { [%clk 0:02:00] } { B15 Caro-Kann Defense: Tartakower Variation } 6. Nf3 { [%clk 0:02:00] } 6... Be6 { [%clk 0:01:57] } 7. Bd3 { [%clk 0:01:57] } 7... Bd6 { [%clk 0:01:56] } 8. h3 { [%clk 0:01:56] } 8... Qc7 { [%clk 0:01:55] } 9. O-O { [%clk 0:01:55] } 9... c5 { [%clk 0:01:54] } 10. dxc5 { [%clk 0:01:54] } 10... Bxc5 { [%clk 0:01:53] } 11. Re1 { [%clk 0:01:48] } 11... O-O { [%clk 0:01:47] } 12. a3 { [%clk 0:01:39] } 12... Qb6 { [%clk 0:01:45] } 13. Be3 { [%clk 0:01:35] } 13... Bxe3 { [%clk 0:01:42] } 14. Rxe3 { [%clk 0:01:35] } 14... Qxb2 { [%clk 0:01:41] } 15. Nd4 { [%clk 0:01:27] } 15... Re8 { [%clk 0:01:25] } 16. a4 { [%clk 0:01:13] } 16... Bd5 { [%clk 0:01:16] } 17. Rb1 { [%clk 0:01:07] } 17... Rxe3 { [%clk 0:00:41] } 18. Rxb2 { [%clk 0:01:04] } 18... Re8 { [%clk 0:00:39] } 19. Qh5 { [%clk 0:00:57] } 19... g6 { [%clk 0:00:37] } 20. Qxd5 { [%clk 0:00:56] } { Black resigns. } 1-0
```

There's a space between the `{` and `[` which unfortunately breaks your nice regex.

Can you think of an elegant regex fix for this? I was thinking about something like `((?<!(\{\s*))\[(.+)\])+` but apparently that doesn't work because lookbehinds have to be a fixed length.

Alternatively I could just find the index of the first `{` and not allow matching after that, but that break if there was a meta tag with `{` in it.

**Comment by alexobviously** [comment]
Okay, this works actually: `(\[(.+)\s"(.+)"\])+`, and seems more robust too. This can only break if a move comment contains a square bracket interior that looks exactly like a header (i.e. {[Something "Something"]}), and I think that would never happen?

**Comment by alexobviously** [comment]
This is now live in version `1.2.6`, let me know if this meets all your requirements and I'll close this issue if so!

**Comment by deathcoder** [comment]
thanks @alexobviously i'll try to test it today and let you know

**Comment by deathcoder** [comment]
it works 🙌 thanks @alexobviously for releasing this so quickly
